name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GCP
        run: |
          gcloud auth activate-service-account --key-file=service-account-key.json
          gcloud config set project YOUR_PROJECT_ID
          gcloud app deploy --quiet
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.unisynbe-410812 }}
          GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GCLOUD_PROJECT }}

